name: Documentation

on:
  push: # (or pull requests)
    paths:
      - "main"
      - ".github"

env:
  FILE_NAME: namaste-javascript-notes

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Create output directory
        run: |
          mkdir pdfs  # create output dir

      - name: Create PDF
        uses: docker://pandoc/latex:2.10
        with:
          args: --pdf-engine=xelatex --output=pdfs/${{env.FILE_NAME}}.pdf main/lectures.md

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: pdfs

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: pdf-generate
          delete-branch: true
          title: "Pdf attached"
          labels: |
            automated pr
