name: Documentation

on:
  push:
    branches: [master]

env:
  FILE_NAME: namaste-javascript-notes

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Create output directory
        run: |
          mkdir pdfs  # create output dir
          ls

      - name: Create PDF
        uses: docker://pandoc/latex:2.10
        with:
          args: --pdf-engine=xelatex --output=pdfs/${{env.FILE_NAME}}.pdf main/lectures.md

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: pdfs
          path: pdfs
