name: Documentation

on:
  push:
    branches: [master]

env:
  FILE_NAME: namaste-javascript-notes

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Create output directory
        run: |
          mkdir output  # create output dir
          ls

      - name: Create PDF
        uses: docker://pandoc/latex:2.10
        with:
          args: --pdf-engine=xelatex --output=output/${{env.FILE_NAME}}.pdf main/lectures.md

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v0.1 #${ github.ref }
          release_name: Release v0.1 #${ github.ref }
          draft: true
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${ steps.create_release.outputs.upload_url }
          asset_path: output/${{env.FILE_NAME}}.pdf
          asset_name: Handbook.pdf
          asset_content_type: application/pdf
