name: Documentation

on:
  push:
    branches: [master]

env:
  FILE_NAME: namaste-javascript-notes

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Create output directory
        run: |
          mkdir output  # create output dir
          ls

      - name: Create PDF
        uses: docker://pandoc/latex:2.10
        with:
          args: --pdf-engine=xelatex --output=output/${{env.FILE_NAME}}.pdf main/lectures.md

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          COMMIT_MESSAGE: Add .pdf files.
          PULL_REQUEST_TITLE: Add .pdf files.
          PULL_REQUEST_BRANCH: pdf-add
          PULL_REQUEST_BODY: ":wave: Here are the .pdf files you requested."
