name: Upload Document as Artifact

on: [push]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish PDF Document
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: "notes/lectures.md"
      - name: Upload Document
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: "lectures.pdf"
          path: "pdfs/"
