name: MD to PDF HTML
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: main
          output_dir: pdfs
          images_dir: assets
      - uses: actions/upload-artifact@v1
        with:
          name: notes
          path: pdfs
